[bugfix] fix get mtp loss bug
Co-authored-by: Crystal-jiang<934889998@qq.com>



# message auto-generated for no-merge-commit merge:
!2549 merge fix_mtp_loss_bug into master

[bugfix] fix get mtp loss bug

Created-by: song_hello_world
Commit-by: Crystal-jiang
Merged-by: ascend-robot
Description: ## What this PR does / why we need it?

修复了拉起kimi训练会报错的问题，AttributeError: 'LLavaCausalLMOutputWithPast' object has no attribute 'mtp_loss'。
related to https://gitcode.com/Ascend/MindSpeed-MM/issues/415

## Does this PR introduce any user-facing change?

No.

## How was this patch tested?

修改后能成功拉起训练。

See merge request: Ascend/MindSpeed-MM!2549